- sibilant/_builtins.lspy
> fixes for defimport and impl of defmimportfrom

- sibilant/_bootstrap_builtins.py
- sibilant/compiler/__init__.py
Adds __repr__ to Special and Macro classes.
> Closes #15

- sibilant/_builtins.lspy
- sibilant/compiler/__init__.py
- tests/builtins.py
- tests/compiler.py
* ```set-var``` renamed to ```setq```
* ```getf``` renamed to ```attr```
* ```setf``` renamed to ```set-attr```
* ```set!``` renamed to ```setf```
* added ```gv-define-setter-fn```, ```gv-define-setter```, ```gv-define-simple-setter```
* define some basic ```setf``` forms using new gv-define... calls
Closes #19
> Updates to setf, setq, set-attr, attr

- sibilant/__init__.py
* make Symbol interning via weakref
* adds a stub Keyword type for later use
Closes #23
> make Symbol interning via weakref

- sibilant/_bootstrap_builtins.py
- sibilant/ast.py
- sibilant/compiler/__init__.py
- tests/__init__.py
- tests/ast.py
- tests/compiler.py
> keyword literal type

- sibilant/__init__.py
- sibilant/parse.py
> use flexible atom matching instead of hard-coded matches

- sibilant/compiler/operators.py
- sibilant/parse.py
- tests/parse.py
> unquote and unquote-splicing only available as reader macros inside of quasiquote

- sibilant/_bootstrap_builtins.py
- sibilant/_builtins.lspy
- sibilant/compiler/__init__.py
- sibilant/compiler/specials.py
- sibilant/parse.py
> higher order macros, regex atom matching and conversion, and a c__r impl

- sibilant/compiler/specials.py
- tests/compiler/__init__.py
- tests/compiler/specials.py
* `try` no longer creates a nested-function
* additional unit tests to attempt to trigger any potential stack issues
Closes #5
> inlined try special

- sibilant/compiler/operators.py
- tests/compiler/operators.py
> unittest coverage for sibilant.compiler.operators

- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/compiler/specials.py
* support for keyword and default value formals
* support for keyword parameter values in function calls
* special keyword *: for variadic args iterable
* special keyword **: for variadic keyword map
Closes #25
> keyword formans and function parameters

- sibilant/__init__.py
- sibilant/compiler/__init__.py
> split keyword and symbol inheritance

- examples/sample-project/setup.py
- examples/sample-project/sibsampl/__init__.py
- examples/sample-project/sibsampl/cli.lspy
> contrived example to show how to use sibilant from a separate project

- sibilant/compiler/operators.py
- sibilant/compiler/specials.py
- tests/compiler/specials.py
> raise as an operator, with a runtime binding

- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/compiler/specials.py
- tests/compiler/specials.py
* rewrote the ```special_try``` to use the new blocks
* rewrote ```special_cond``` and ```special_with``` as well
* updates to ```max_stack``` sizing based on python opcode affects from dis
* add ```__del__``` cleanup to CodeSpace and the new CodeBlock types
Closes #67
> Break up pseudop code into block segments, with individual max_stack calculations.

- sibilant/__init__.py
- sibilant/compiler/__init__.py
- sibilant/compiler/specials.py
- sibilant/module.py
- sibilant/parse.py
- tests/parse.py
> Move position data onto Pair

- sibilant/__init__.py
- sibilant/_bootstrap_builtins.py
- sibilant/compiler/specials.py
* created copy-pair, join-pairs, build-unpack-pair
* updated unquote splicing to use the new build-unpack-pair
Closes #71
> unquote splice preserves src position data

- sibilant/compiler/specials.py
- tests/compiler/specials.py
> easy implementation of named let form

- sibilant/_bootstrap_builtins.py
- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/compiler/operators.py
- sibilant/compiler/specials.py
* updated _bootstrap_builtins to hide all but what we want to export
* added better type predicates to builtins
* cleaned up get/set/del for local/variable/var/item/attr
* moved set-item and del-item to operators
Closes #75
Closes #76
> builtins cleanup and item operators

- sibilant/_builtins.lspy
- sibilant/compiler/__init__.py
- sibilant/compiler/specials.py
* moved macroexpand-1 from specials.py to _builtins.lspy
* added macroexpand (applies expansion over and over...)
* fixed empty position data for macrolet expansion at the head of a pair
Closes #63
> fixed runtime macroexpansion

- sibilant/parse.py
- tests/parse.py
* eg. 5e2 1.5e-1 5.e10
Closes #95
> exponent float support

- examples/reader-macro.lspy
- sibilant/_builtins.lspy
- sibilant/compiler/specials.py
- sibilant/parse.py
- tests/compiler/tco.py
- tests/sibilant/builtins.lspy
* implemented flet and labels as macros, Closes #89
* see http://www.lispworks.com/documentation/HyperSpec/Body/s_flet_.htm
* minor string parsing tweak
* made doc special work for classes and modules Closes #96
> flet and labels macros

- sibilant/compiler/__init__.py
> don't call clear() from del

- sibilant/_builtins.lspy
- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/compiler/specials.py
- tests/compiler/specials.py
> setq-values and let-values for structured assignment

- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/compiler/specials.py
- tests/compiler/specials.py
* implemented for-iter, using the FOR_ITER opcode
* with unit tests
Closes #59
> for-iter special form

- sibilant/_builtins.lspy
- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/compiler/specials.py
- tests/compiler/__init__.py
- tests/compiler/specials.py
* adds return special
* adds yield special
* adds yield-from special
Closes #99
> implementing yield, yield-from, return

- sibilant/compiler/__init__.py
- tests/compiler/__init__.py
* I may want to revisit this later (the entire formals/parameter thing) but for now it's working
Closes #117
> support for kwonly formals with the empty variadic form

- examples/sibilant-life/README.md
- examples/sibilant-life/setup.py
- examples/sibilant-life/siblife/__init__.py
- examples/sibilant-life/siblife/cli.lspy
- examples/sibilant-life/siblife/curse.lspy
- examples/sibilant-life/siblife/life.lspy
- sibilant/_bootstrap_builtins.py
- sibilant/compiler/specials.py
* sibilant-curses-life is an example project towards Issue #2 
* siblife can be installed as a package
* siblife also becomes the name of a CLI invocation to start the curses life game.
* found an issue with for-each, in that it did not declare its unpacked bindings locally. forced it to do so, which Closes #120
> Example life game

- sibilant/_builtins.lspy
- tests/builtins.py
* convert eval and compile macros to use the new module API
* author unit tests to ensure that eval and compile work when they should
* added docstrings
Closes #108
> Fix eval and compile builtin macros

- sibilant/_bootstrap_builtins.py
- sibilant/_builtins.lspy
- sibilant/compiler/__init__.py
- tests/builtins.py
* adds (item-slice sequence start stop step)
* adds (setf (item-slice sequence start stop step) value)
* adds (active-compiler)
* allows None in place of env for macroexpandq
* unittests for setf item-slice
Closes #126
> item-slice macro

- sibilant/_bootstrap_builtins.py
- tests/sibilant/builtins.lspy
> fixes build-dict and adds unittests

- setup.py
- sibilant/__init__.py
- sibilant/_bootstrap_builtins.py
- sibilant/ctypes.c
- sibilant/ctypes.h
- sibilant/parse.py
- tests/__init__.py
* keyword, symbol, pair
* cons, car, cdr, setcar, setcdr
* merge_pairs, build_unpack_pair
* reapply, build_tuple
Closes #133
> Ported core types and functions to native extensions

- .gitignore
- ideas/values_idea.py
- include/py3-sibilant.h
- sibilant/__init__.py
- sibilant/_types.c
- sibilant/bootstrap.py
- sibilant/operators.py
- tests/types.py
values is a type which when instantiated accepts any number of
positional and keyword arguments. The tuple and dictionary
representing those arguments are stored within the values instance.
The values instance supports the sequence protocol, allowing access to
the positional arguments, and it supports the mapping protocol,
allowing access to the keyword arguments. The values instance is also
callable. When called, the first argument must be a function. The
function will them be invoked with the values object's args and
keywords, plus any additiona positional or keyword arguments supplied.
- values native type
- unit tests for same
- some minor readability fixes for _types.c
- typographical error for exported repeatedly function
> New values type.

- sibilant/bootstrap.py
- sibilant/parse.py
- tests/parse.py
* 1.5 1. .5  are all floats (stays the same as existing code)
* 1.5f 1.f .5f  are also floats (alternate explicit syntax)
* 1.5d 1.d .5d  are now decimal.Decimal values
Closes #170
> Support for decimal numbers

- sibilant/parse.py
- tests/parse.py
* added support for triple-quoted string literals
* added unit tests for same
Closes #177
> Triple-quoted string literals

- sibilant/basics.lspy
- sibilant/compiler/__init__.py
- sibilant/compiler/cpython35.py
- sibilant/compiler/cpython36.py
- sibilant/operators.py
- tests/operators.py
* compiler support for the BUILD_SLICE opcode
* build-slice operator using BUILD_SLICE at compile-time and slice and
run-time
* unit-tests for new build-slice operator
* updated item-slice macro to use build-slice
Closes #185
> build-slice operator

- sibilant/importlib.py
> __init__.lspy importer support

- sibilant/compiler/__init__.py
pseudop_pop will now check if the precevious operation was a CONST
load. If so, the operation will be removed and no POP operation will
be added. If not, the POP operation will be added as per usual.
This behavior is gated behind a new boolean attribute of the CodeSpace
class, named compress_const_pop.
The purpose is to remove useless churn, such as a number of
CONST(None), POP() calls inside a begin block.
Closes #194
> compress CONST, POP ops together

- sibilant/operators.py
- tests/operators.py
> bitwise-and bitwise-or bitwise-xor now all take 2 or more arguments and will reduce the operation from left to right

- sibilant/basics.lspy
- sibilant/bootstrap.py
- tests/basics.py
* macro providing (has-attr OBJ ATTRSYM)
* unit tests for same
> has-attr via patch from ahills

- examples/sibilant-life/siblife/life.lspy
- ideas/tcr.txt
- sibilant/basics.lspy
- sibilant/bootstrap.py
- sibilant/builtins.py
- sibilant/compiler/__init__.py
- sibilant/lib/__init__.py
- sibilant/lib/tco.c
- sibilant/operators.py
- sibilant/pseudops/__init__.py
- sibilant/pseudops/stack.py
- sibilant/pseudops/targets/cpython35.py
- sibilant/pseudops/targets/cpython36.py
- sibilant/specials.py
* adds jump_if_false_or_pop, jump_if_true_or_pop pseudops
* adds a helper for resetting current frame's local and cell vars.
this is ever so slightly less expensive than a full trampoline
bounce
* makes use of tailcall-full in some situations
> Poking around with tail-recursive implementations.

- sibilant/bootstrap.py
- sibilant/lib/__init__.py
- sibilant/lib/tco.c
- tests/tco.py
* Add a trampoline? predicate to the builtins
* Add default passthrough on all attributes to the underlying function
Fixes: #215
> Better trampoline attributes

- sibilant/basics.lspy
- sibilant/lib/__init__.py
- sibilant/parse.py
> default f-string support in the reader
