sibilant/compiler/__init__.py

* added sibilant.compiler.simple_parameters to collect source params
in a form that python can invoke from
* updated Macro.compile to unpack source parameters before passing to
the expand function for expansion
Closes #54

macros can now receive keyword arguments

---

sibilant/_builtins.lspy
sibilant/compiler/__init__.py
sibilant/compiler/specials.py
tests/compiler/__init__.py

* only inject the cons conversion step for functions which have improper formals
* only gather_parameters for macro expansion when the formals for the macro are proper. This will allow macros to take flexible keywords as the source to expand
* decorate macros to enable checking for the above at expand time.
Closes #57

limit vararg conversion to only functions with symbol or improper formals

---

sibilant/_builtins.lspy
sibilant/compiler/__init__.py
sibilant/compiler/specials.py
tests/compiler/specials.py

This also unifies binding clauses across let, with, and catch clauses to
(SYMBOL EXPRESSION) or (EXPRESSION as: SYMBOL) or for when the binding is optional (with and catch clauses) just (EXPRESSION)
Closes #48

Use :else :finally keywords for cond and try

---

sibilant/_bootstrap_builtins.py
sibilant/_builtins.lspy
sibilant/compiler/__init__.py

* provide the python originals as py-eval and py-compile
* compile will work on strings, streams, and sibilant source objects such as cons pairs, symbols, and self-evaluating types
Closes #80

macros for eval and compile

---

examples/sample-project/sibsampl/cli.lspy
sibilant/_builtins.lspy
sibilant/compiler/__init__.py
sibilant/compiler/specials.py
sibilant/module.py
sibilant/repl.py
tests/compiler/specials.py

* define in the module scope is a global define
* define otherwise is a local define
* define-global remains for forcing a global define
* var added as alias for define
* CodeSpace gained a mode parameter, to differentiate module vs. expression
* updated sample code
* created def, a generic form of define which will allow new binding functions to add scopes and targets at runtime
Closes #21

define is scope aware

---

examples/reader-macro.lspy
sibilant/_bootstrap_builtins.py
sibilant/_builtins.lspy
sibilant/compiler/tco.py
tests/sibilant/__init__.py
tests/sibilant/builtins.lspy

* method macro removed
* class macro uses locals call
* added tco_disable to prevent TCO trampoline bounces on locals and globals
* added a sibilant-native unittest
* fixed def class (was def classy)
Closes #84

class macro now uses locals to populate members. remove method macro.

---

ideas/todo-time
sibilant/_builtins.lspy
sibilant/builtins.py
sibilant/cli.py
sibilant/importlib.py
sibilant/module.py
tests/module.py

* added a compile_to_file function to sibilant.module
* added a -C option to the sibilant CLI which compiles the specified source to a .pyc file
* tweaked some read-time calls to not presume that __reader__ is always present (since it isn't when the module is pre-compiled)
* thought about people I wanted to forget, so had two mimosas and went somewhere else
* had more ideas to clean up the parse/compile/run time stages, but will implement those separately. For now there's a new file in ideas documenting it
* verified thay Python will load these .pyc files without complaint, and without needing the sibilant source importer enabled.
Closes #8

implement compile-to-file

---

sibilant/_builtins.lspy
sibilant/builtins.py
sibilant/cli.py
sibilant/compiler/__init__.py
sibilant/importlib.py
sibilant/module.py
sibilant/parse.py
sibilant/repl.py
tests/builtins.py
tests/compiler/__init__.py
tests/compiler/specials.py
tests/compiler/tco.py
tests/module.py

* splits up module API based on parse, compile, run times Closes #90
* updates everything that used iter_compile to use the new module API
* updated unittests
* some work on parse to support readahead instead of tell/seek (supporting more stream types, hopefully async pipe in the future) Closes #91

Module Parse, Compile, and Runtime cleanup

---

sibilant/_bootstrap_builtins.py
sibilant/compiler/tco.py

* only tailcall when _tco_enabled is set to True on the function
* trampolines set _tco_enabled to True
* the tco_disable function now sets _tco_enabled to False
* fix the qualified names of trampoline, tailcall and tco_disable
Closes #103

Perform more selective bouncing in tailcall positions.

---

sibilant/_builtins.lspy
sibilant/compiler/__init__.py
sibilant/compiler/cpython35.py
sibilant/compiler/cpython36.py
sibilant/compiler/specials.py

* updates the gather_formals function to collect keyword:default
bindings, and also keyword-only:default bindings for keyword
parameters specified after a positional variadic
* updates the class macro to allos a metaclass keyword as part of the
type parents declarations
Closes #106
Closes #107

kw-only parameters and metaclass in class definitions

---

sibilant/parse.py
tests/compiler/__init__.py
tests/module.py
tests/parse.py

* ditched awful read-ahead impl
* require SourceReader instances to specify filename
Closes #111

Use built-in buffering for seek

---

setup.py

Both `setup.py develop` and `pip install -e` won't install dependencies from `requires`, but they will for `install_requires`.

Use `install_requires` in setup.py instead of `requires`

---

sibilant/__init__.py
sibilant/_bootstrap_builtins.py
sibilant/_builtins.lspy
sibilant/compiler/__init__.py
sibilant/compiler/cpython35.py
sibilant/compiler/cpython36.py
sibilant/compiler/operators.py
sibilant/ctypes.c
tests/sibilant/builtins.lspy

* (build-tuple ARG...) evaluates to a tuple of the arguments
* (build-list ARG...) evaluates to a list of the arguments
* (build-set ARG...) evaluates to a set of the arguments
* (build-dict (KEY VAL)...) evaluates to a dictionary
These can be used at compile time to produce the literal pythonic
expressions using the bytecode operations directly. They can also be
used at run-time to similar effect.
Closes #139

build-tuple, build-list, build-set, and build-dict operators

---

sibilant/__init__.py
sibilant/compiler/__init__.py
sibilant/parse.py

* Re-homed SibilantSyntaxException from sibilant.compiler to sibilant
* add a flag to skip the exec header for parser wrapper functions
* remove useless partial wrappers around atom matchers

Some small tweaks to parser utility functions.

---

include/py3-sibilant.h
sibilant/_types.c
tests/types.py

- add support for hashing values instances
- values with non-hashable positional or keyword contents are not hashable
- values without kwargs hash the same as their tuple equivalents
- added unit tests to verify behavior
Closes #154

Hashing of values objects

---

sibilant/basics.lspy
sibilant/bootstrap.py
sibilant/builtins.py
sibilant/cli.lspy

* assert macro checks sys.flags.optimize level, noop if non-zero
* cli invocation now honors the -O flag to enable optimizations
Closes #169

Support for assert

---

examples/reader-macro.lspy
sibilant/basics.lspy
sibilant/bootstrap.py
sibilant/parse.py

* read-raw receives an atom instead of a processed atomic type
* see examples/reader-macro.lspy for usage
Closes #173

Support for reading raw atoms in reader macros

---

examples/sibilant-life/siblife/curse.lspy
sibilant/basics.lspy
sibilant/operators.py
tests/operators.py
tests/sibilant/basics.lspy

* reverse operator arguments for `in` and `not-in`
* new `contains` and `not-contains` operators
* (contains sequence value)  ::=  (in value sequence) ::=  value in sequence
* (not-contains sequence value) ::= (not-in value sequence) ::= value not in sequence
Closes #179

Reverse ordering on operators `in`, `not-in`

---

sibilant/basics.lspy
sibilant/operators.py
sibilant/specials.py
tests/specials.py

* delq will delete a name, searching from closest namespace outwards
* delq-global will delete a name in the global namespace only
* del-attr will delete an attribute from an instance
* del-item will delete an index or slice from sequence
* delf will dispatch to the appropriate operator
Closes #186

delf, delq-global, del-attr, del-item, delq

---

sibilant/basics.lspy
tests/basics.py

let* is like let except each binding is defined in order, so later
values can refer to earlier ones.
letrec is like let* except the bindings are all created first, then the
values are applied in order, so earlier values can refer to later ones.

Add let* and letrec macros

---

sibilant/basics.lspy
tests/basics.py

Same as let* + let-values! See Lets.test_let_star_values() for example
usage.

Add let*-values macro

---

sibilant/basics.lspy
sibilant/compiler/__init__.py
sibilant/lib.py
tests/sibilant/basics.lspy

* sibilant.compiler.SibilantCompiler gains a tmp_compiled context manager
* sibilant.basics gains a defspecial to create a Special
* sibilant.basics gains macro-let special which creates macros which are
only available during the compile-time of the body element. Syntax is
similar to the flet and labels macros.
* Macros defined by macro-let are ONLY available at compile-time, not at
run-time. They do not declare local fast vars.
* unit tests for macro-let
Closes #128

macro-let for temporary macro definitions

---

sibilant/compiler/__init__.py

make the compiler error with the correct exception when attempting to
evaluate an unquoted improper list
Closes #211

backtrace on unquoted cons invocation

---

sibilant/lib/__init__.py
sibilant/lib/_types.c
sibilant/operators.py

A built-in no-op operator.
* At compile-time, drops all sub-expressions and evaluates to `None`.
* At run-time, accepts `*args` and `**kwds` and returns `None`.

'pass' operator

---

sibilant/lib/atom.c
tests/types.py

Symbols (and gensyms by extension) and keywords respond to len() with
the string length of their name.

Add __len__ to atom types

---

sibilant/specials.py
tests/specials.py

As per the existing docstring, the following two are equivalent:
```
; functions correctly before this patch
(try
(raise! Exception)
[[Exception] (recover)])
; described in docstring
(try
(raise! Exception)
[except: Exception (recover)])
```

Allow use of except: keyword with try

---

sibilant/specials.py
tests/specials.py

When using `define-values` in some situations, a compiler error is triggered. Example reproducer:
```
(define-values [*: v] (values: 1 2 3))
```
would produce
```
UnboundLocalError: local variable 'b' referenced before assignment
```

Fix define-values compiler error
